services:
  - type: web
    name: vaultly-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_URL
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: PUBLIC_API_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
